#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true


GROUP=io.github.nesyou01
POM_ARTIFACT_ID=keditor
VERSION_NAME=0.0.1

POM_NAME=KEditor
POM_DESCRIPTION=A Kotlin Multiplatform video editing library powered by FFmpeg.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/nesyou01/KEditor

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/nesyou01/KEditor
POM_SCM_CONNECTION=scm:git:git://github.com/nesyou01/KEditor.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:nesyou01/KEditor.git

POM_DEVELOPER_ID=ylagmah
POM_DEVELOPER_NAME=Youness Lagmah
POM_DEVELOPER_URL=https://github.com/nesyou01/